# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ad5752f9b592bb84759902f5debf0aa92bdf4a7a70391b6ca41c25948fa7a29ad56828cf64719fcb9370fb9b92cdce87efa3fa2dc6add8f69c88ccf19a49f4e

test:
  secret_key_base: dafc05c8eae1cb41b7b24feefbc2b73d9bec9dc3fb4f092ab4acd284ef147b59c87d0fd338207f71975dc1e3879bdce49ed8e7983135629124b097bfa4a8635d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
